# Generated by Django 5.1.5 on 2025-02-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='department',
            field=models.CharField(choices=[('AG', 'Alto Paraguay'), ('AA', 'Alto Paraná'), ('AM', 'Amambay'), ('AS', 'Asunción'), ('BQ', 'Boquerón'), ('CG', 'Caaguazú'), ('CZ', 'Caazapá'), ('CY', 'Canindeyú'), ('CE', 'Central'), ('CN', 'Concepción'), ('CR', 'Cordillera'), ('GU', 'Guairá'), ('IT', 'Itapúa'), ('MI', 'Misiones'), ('NE', 'Ñeembucú'), ('PG', 'Paraguarí'), ('PH', 'Pdte. Hayes'), ('SP', 'San Pedro')], default='AS', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
